version: '3.8'

services:
  # Dịch vụ Backend (Django)
  backend:
    build:
      context: ../backend
    container_name: predictor_backend
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - 8000
    command: gunicorn Predict_Learning_Web.wsgi:application --bind 0.0.0.0:8000
    depends_on:
      - db

  # Dịch vụ Database (MongoDB)
  db:
    image: mongo:5.0
    container_name: predictor_mongodb
    restart: unless-stopped
    env_file:
      - ../.env
    volumes:
      - mongo_data:/data/db

  # Dịch vụ Nginx (Reverse Proxy)
  nginx:
    image: nginx:1.19.0
    container_name: predictor_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/static
      - media_volume:/app/media
      # Thêm volume cho certbot ở Giai đoạn 5
      # - certbot_conf:/etc/letsencrypt
      # - certbot_www:/var/www/certbot
    depends_on:
      - backend

# Định nghĩa volumes
volumes:
  mongo_data:
  static_volume:
  media_volume:
    # certbot_conf:
    # certbot_www:
